### ISSUE TITLE
RetreiveUsersByEmail should not return a list

### ISSUE THREAD

**Issue by mrxbox98** [mattmalec/Pterodactyl4J#30]
You cannot create multiple accounts with the same email address so RetreiveUsersByEmail does not need to return a list.

**Comment by TheSilentPro** [comment]
Yeah it does
https://dashflo.net/docs/api/pterodactyl/v1/#req_5703791f721f4b50bb0318cf19e2262d

**Comment by mrxbox98** [comment]
When getting users with an email it does return a list but that list should have only 1 user since you cant create 2 users with 1 email.

**Comment by lokerhp** [comment]
> When getting users with an email it does return a list but that list should have only 1 user since you cant create 2 users with 1 email.

The API returns a list of users and since you can also get users by only a part of their email address (It uses contains and not equals):
`newUsers = newUsers.filter(u -> u.getEmail().contains(email));`

So its needed to return a list since there can be multiple users with @gmail.com in their email for example

**Comment by mattmalec** [comment]
If you need a single ApplicationUser instead of a List, you can always wrap the List in a Stream and utilize findFirst()
