### ISSUE TITLE
How to get a Status from a ApplicationServer

### ISSUE THREAD

**Issue by ghost** [mattmalec/Pterodactyl4J#56]
I didn´t found a way to get a Status (like "ONLINE") from a ApplicationServer

**Comment by Goksi** [comment]
Currently, pterodactyl api doesn't have way to get server status from application endpoints, according to that, P4J doesn't have a way to provide that. You would have to use client api to achieve that. As from 1.8 panel version it shouldn't be much problem for your app because you can use client key for application endpoints.

**Comment by luiz-otavio** [comment]
You can retrieve that from [resources usage endpoint](https://dashflo.net/docs/api/pterodactyl/v1/#req_a8875d2840c64cbdb40e9bdb6cba4f75).
